
//===================//
// ANALLAT_enum       //
//===================//

enum COMPLEX{REAL,IMAG};
enum CLASS_ENUM{CORR_SINGLE, CORR_MAT, CORR_THREEPT};
enum FILE_FORMAT{ASCII_FORMAT, HDF5_FORMAT, DEFAULT_FORMAT};
enum CREATOR{JGREEN, GSILVI, SPAUL};
enum WHICHPARTICLE{PROTON, NEUTRON, BARYON, DIBARYON, PION, CURRENT};
enum RESAMPLE_TYPE{BOOTSTRAP, JACKKNIFE};
enum FITMODEL{LINEAR, LOGLINEAR, EXPONENTIAL, TWO_EXPONENTIAL};
